export const text = {
    referrals: { es: "Remisones" },
    number_remission: { es: "N° Remisión"},
    client: { es: "Cliente" },
    description: { es: "Descripción" },
    date: { es: "Fecha" },
    remision: { es: "REMISIÓN" },
    bussines: { es: "Empresa" },
    deliver_to: { es: "Entregar a" },
    address: { es: "Dirección" },
    email: { es: "Correo" },
    order: { es: "Órden" },
    tell: { es: "Teléfono" },
    taker: { es: "Tomador" },
    policy: { es:"Póliza"},
    branch: { es:"Sucursal/Agen??"},
    quantity: { es:"Cantidad"},
    association: { es:"Asociación de padres de hogares comunitarios de bienestar. Cerro La Cruz"},
    total: { es:"Total"},
    received: { es:"Recibido a satisfacción por"},
    does_not_record: { es:"No registra"},
    produced_by: { es:"Elaborado por"},
    reception: { es:"Recepción"},
    remove: { es:"Eliminar"},
    print: { es:"Imprimir"},
    new_remision: { es:"NUEVA REMISIÓN"},
    format_app: { es:"Formato de APP"},
    format_add: { es:"Formato y adjuntos"},
    deliver: { es:"Entregar"},
    additional_columns: { es:"Columnas adicionales:"},
    number_policy: { es:"Número de póliza"},
    agency: { es:"Sucursal/Agencia"},
    files_add: { es:"Archivos adjuntos:"},
    drag_or: { es:"Arrastra o"},
    add_here: { es:"adjunta aquí"},
    file: { es:"los archivos"},
    select: { es:"Selecciona una o varias órdenes"},
    forwarded: { es:"Remisionada"},
    balance: { es:"Saldo"},
    forward: { es:"Remisionar"},
    Test: { es:"Prueba: Seguros del Estado"},
    generate_referral: { es:"Generar Remision"},
    my_referral : { es:"Mis remisiones"},
    new_referral: { es:"Nueva remisión"},
    s_referral: { es:"Buscar remisión"},



  };
  