export const text = {
  number_of: { es: 'Número de...' },
  id: { es: ' Identificación' },
  card: { es: ' Tarjeta' },
  order: { es: 'Orden' },
  policy: { es: 'Póliza' },
  apply_filter: { es: 'Aplicar filtro' },
  acept: { es: 'Aceptadas' },
  prints: { es: 'Impresas' },
  finished: { es: 'Finalizadas' },
  eliminated: { es: 'Eliminadas' },
  order_list: { es: 'Listado de pedidos' },
  my_orders: { es: 'Mis órdenes' },
  inform: { es: 'informe' },
  s_search: { es: 'Buscar orden' },
  report: { es: 'INFORME' },
  n_ordern: { es: 'N° Orden' },
  client: { es: 'Cliente' },
  branch_office: { es: 'Sucursal' },
  fisic: { es: 'Física' },
  id_m: { es: 'ID Mobile' },
  card_pdf: { es: 'Carné PDF' },
  date: { es: 'Fecha' },
  state: { es: 'Estado' },
  download_pdf: { es: 'Descargar en PDF' },
  download_excel: { es: 'Descargar en Excel' },
  bussnies: { es: 'Empresa' },
  users: { es: 'Usuarios' },
  start_date: { es: 'Fecha inicio' },
  end_date: { es: 'Fecha final' },
  search: { es: 'Buscar' },
  user: { es: 'Usuario' },
  order_details: { es: 'Detalles de Orden' },
  id_fisica: { es: 'ID Física' },
  details: { es: 'Detalles ->' },
  observations: { es: 'Observaciones' },
  test: { es: 'Prueba de visaualizacion de comentario' },
  remission: { es: 'Remision' },
  quantity: { es: 'Cantidad' },
  date_range: { es: 'Rango de fecha...' },
  taker: { es: 'Tomador' },
  reference: { es: 'Referencia' },
  add_reference: { es: 'Añadir Referencia' },
  comments: { es: 'Comentarios' },
  add_observations: { es: 'Agregar Observación (Opcional)...' },
  n_of: { es: 'Número de...' },
  id_branch_office: { es: 'ID Sucursal' },
  start: { es: 'Inicio' }
}
