/* eslint-disable no-unused-vars */
export enum SCREENS_ENUM {
  LOGIN = 'LOGIN',
  FORGET_PASSWORD = 'FORGET_PASSWORD',
  VERIFICATION = 'VERIFICATION',
  CHANGE_PASSWORD = 'CHANGE_PASSWORD',
  PASSWORD_UPDATED = 'PASSWORD_UPDATED'
}
