export enum ESTADOS_USUARIO_CAMPANIA {
    INSCRITO = 1,
    DEBO_PUBLICAR = 2,
    SUBIR_PANTALLAZOS = 3,
    PANTALLAZOS_EN_REVISION = 4,
    PANTALLAZOS_RECHAZADOS = 5,
    TERMINADA_SATISFACTORIAMENTE = 6,
    TERMINADA_INSATISFACTORIAMENTE = 7
}