export const text = {
    title: {es:'EDITAR USUARIO'},
    acount: {es:'Tipo de cuenta'},
    name: {es:'Nombre'},
    business: {es:'Empresa'},
    lastName: {es: 'Apellido'},
    email: {es: 'Correo'},
    IDuser: {es: 'ID usuario'},
    direction: { es: "Dirección" },
    telefono: { es: "Teléfono" },
    state: {es: 'Estado'},
    password: {es: 'Contraseña'},
    permissions: {es: 'Permisos'},
    picture: {es: 'Fotografia'},
    cancelButton: {es: "Cancelar"},
    updateButton: {es: "Actualizar"},
    message: {es: 'Arrastrar o '},
    messageIN: {es: 'adjuntar aqui'},
    message2: {es: 'los archivos'}
}
