export const text = {
    title: {es:'USUARIO'},
    subtitle: {es: "Datos del usuario"},
    acount: {es:'Cuenta'},
    name: {es:'Nombre'},
    lastName: {es: 'Apellido'},
    email: {es: 'Correo'},
    user: {es: 'Usuario'},
    state: {es: 'Estado'},
    id: {es: "Codigo"},
    password: {es: 'Contraseña'},
    permissions: {es: 'Permisos'},
    picture: {es: 'Fotografia'},
    habilitate: {es: "Activar"},
    inhabilitate: {es: "Desactivar"},
    active: {es: "ACTIVO"},
    inactive: {es: "INACTIVO"},
    editButton: {es: "Editar"},
    deleteButton: {es: "Eliminar"},
    nit: {es: 'NIT'},
    address: {es: "Direccion"},
    telphone: {es: "Telefono"},
    subtitleUsers: {es: "Usuarios del cliente"},
    subtitleBranch: {es: "Sucursales del cliente"}
}
